name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Describe the issue...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      placeholder: |
        1. Create a Website with...
        2. Call crawl()...
        3. Observe...
      render: rust
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Spider version
      placeholder: "2.45.24"
    validations:
      required: true
  - type: dropdown
    id: features
    attributes:
      label: Rendering mode
      options:
        - HTTP (default)
        - Chrome (CDP)
        - WebDriver
        - Smart mode
        - Not applicable
    validations:
      required: true
  - type: input
    id: rust-version
    attributes:
      label: Rust version
      placeholder: "Output of `rustc --version`"
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g. macOS 15, Ubuntu 24.04, Windows 11"
